language: generic 
sudo: required
services:
  - docker
before_install: 
  - docker build -f Dockerfile.dev -t ungvert/docker-react .
script:
  - docker run -e CI=true ungvert/docker-react npm run test -- --coverage