FROM node:alpine

WORKDIR '/app'

COPY ./package.json .
RUN npm install
COPY . .

CMD ["npm","start"]

# docker build -f Dockerfile.dev -t ungvert/cra .
# docker run --rm -it -p 3000:3000 -v "$(pwd -W):/app" ungvert/cra
